/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenDto from './TokenDto';
import UserDto from './UserDto';

/**
* The AuthenticationInfoDto model module.
* @module model/AuthenticationInfoDto
* @version 1.0.1-SNAPSHOT
*/
export default class AuthenticationInfoDto {
    /**
    * Constructs a new <code>AuthenticationInfoDto</code>.
    * @alias module:model/AuthenticationInfoDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AuthenticationInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthenticationInfoDto} obj Optional instance to populate.
    * @return {module:model/AuthenticationInfoDto} The populated <code>AuthenticationInfoDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationInfoDto();
                        
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserDto.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = TokenDto.constructFromObject(data['token']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UserDto} user
    */
    'user' = undefined;
    /**
    * @member {module:model/TokenDto} token
    */
    'token' = undefined;




}
