/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ChangePasswordDto model module.
* @module model/ChangePasswordDto
* @version 1.0.1-SNAPSHOT
*/
export default class ChangePasswordDto {
    /**
    * Constructs a new <code>ChangePasswordDto</code>.
    * @alias module:model/ChangePasswordDto
    * @class
    * @param newPassword {String} 
    */

    constructor(newPassword) {
        
        
        this['newPassword'] = newPassword;
        
    }

    /**
    * Constructs a <code>ChangePasswordDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChangePasswordDto} obj Optional instance to populate.
    * @return {module:model/ChangePasswordDto} The populated <code>ChangePasswordDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePasswordDto();
                        
            
            if (data.hasOwnProperty('oldPassword')) {
                obj['oldPassword'] = ApiClient.convertToType(data['oldPassword'], 'String');
            }
            if (data.hasOwnProperty('newPassword')) {
                obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} oldPassword
    */
    'oldPassword' = undefined;
    /**
    * @member {String} newPassword
    */
    'newPassword' = undefined;




}
