/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CredentialsDto model module.
* @module model/CredentialsDto
* @version 1.0.1-SNAPSHOT
*/
export default class CredentialsDto {
    /**
    * Constructs a new <code>CredentialsDto</code>.
    * @alias module:model/CredentialsDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CredentialsDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CredentialsDto} obj Optional instance to populate.
    * @return {module:model/CredentialsDto} The populated <code>CredentialsDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CredentialsDto();
                        
            
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * @member {String} password
    */
    'password' = undefined;




}
