/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ErrorDto model module.
* @module model/ErrorDto
* @version 1.0.1-SNAPSHOT
*/
export default class ErrorDto {
    /**
    * Constructs a new <code>ErrorDto</code>.
    * @alias module:model/ErrorDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ErrorDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorDto} obj Optional instance to populate.
    * @return {module:model/ErrorDto} The populated <code>ErrorDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorDto();
                        
            
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('messge')) {
                obj['messge'] = ApiClient.convertToType(data['messge'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} timestamp
    */
    'timestamp' = undefined;
    /**
    * @member {Number} status
    */
    'status' = undefined;
    /**
    * @member {String} error
    */
    'error' = undefined;
    /**
    * @member {String} messge
    */
    'messge' = undefined;
    /**
    * @member {String} path
    */
    'path' = undefined;




}
