/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SettingsDto model module.
* @module model/SettingsDto
* @version 1.0.1-SNAPSHOT
*/
export default class SettingsDto {
    /**
    * Constructs a new <code>SettingsDto</code>.
    * @alias module:model/SettingsDto
    * @class
    * @param wantsAi {Boolean} 
    * @param emailReceive {Boolean} 
    */

    constructor(wantsAi, emailReceive) {
        
        
        this['wantsAi'] = wantsAi;
        this['emailReceive'] = emailReceive;
        
    }

    /**
    * Constructs a <code>SettingsDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SettingsDto} obj Optional instance to populate.
    * @return {module:model/SettingsDto} The populated <code>SettingsDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettingsDto();
                        
            
            if (data.hasOwnProperty('wantsAi')) {
                obj['wantsAi'] = ApiClient.convertToType(data['wantsAi'], 'Boolean');
            }
            if (data.hasOwnProperty('emailReceive')) {
                obj['emailReceive'] = ApiClient.convertToType(data['emailReceive'], 'Boolean');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} wantsAi
    */
    'wantsAi' = undefined;
    /**
    * @member {Boolean} emailReceive
    */
    'emailReceive' = undefined;
    /**
    * @member {String} emailAddress
    */
    'emailAddress' = undefined;
    /**
    * @member {String} payload
    */
    'payload' = undefined;




}
