/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TokenDto model module.
* @module model/TokenDto
* @version 1.0.1-SNAPSHOT
*/
export default class TokenDto {
    /**
    * Constructs a new <code>TokenDto</code>.
    * @alias module:model/TokenDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TokenDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TokenDto} obj Optional instance to populate.
    * @return {module:model/TokenDto} The populated <code>TokenDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenDto();
                        
            
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('expiration')) {
                obj['expiration'] = ApiClient.convertToType(data['expiration'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token
    */
    'token' = undefined;
    /**
    * @member {String} expiration
    */
    'expiration' = undefined;




}
