/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChangePasswordDto from './ChangePasswordDto';
import SettingsDto from './SettingsDto';

/**
* The UserDto model module.
* @module model/UserDto
* @version 1.0.1-SNAPSHOT
*/
export default class UserDto {
    /**
    * Constructs a new <code>UserDto</code>.
    * @alias module:model/UserDto
    * @class
    * @param username {String} 
    * @param realm {module:model/UserDto.RealmEnum} 
    * @param settings {module:model/SettingsDto} 
    */

    constructor(username, realm, settings) {
        
        
        this['username'] = username;
        this['realm'] = realm;
        this['settings'] = settings;
        
    }

    /**
    * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDto} obj Optional instance to populate.
    * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDto();
                        
            
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('realm')) {
                obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
            }
            if (data.hasOwnProperty('passwordDto')) {
                obj['passwordDto'] = ChangePasswordDto.constructFromObject(data['passwordDto']);
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = SettingsDto.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * @member {String} fullName
    */
    'fullName' = undefined;
    /**
    * @member {module:model/UserDto.RealmEnum} realm
    */
    'realm' = undefined;
    /**
    * @member {module:model/ChangePasswordDto} passwordDto
    */
    'passwordDto' = undefined;
    /**
    * @member {module:model/SettingsDto} settings
    */
    'settings' = undefined;
    /**
    * @member {module:model/UserDto.RoleEnum} role
    */
    'role' = undefined;
    /**
    * @member {Date} expirationDate
    */
    'expirationDate' = undefined;



    /**
    * Allowed values for the <code>realm</code> property.
    * @enum {String}
    * @readonly
    */
    static RealmEnum = {
        /**
         * value: "LOCAL"
         * @const
         */
        "LOCAL": "LOCAL",
        /**
         * value: "LDAP"
         * @const
         */
        "LDAP": "LDAP",
        /**
         * value: "MEMORY"
         * @const
         */
        "MEMORY": "MEMORY",
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN": "UNKNOWN"    };
    /**
    * Allowed values for the <code>role</code> property.
    * @enum {String}
    * @readonly
    */
    static RoleEnum = {
        /**
         * value: "DEFAULT"
         * @const
         */
        "DEFAULT": "DEFAULT",
        /**
         * value: "ADMIN"
         * @const
         */
        "ADMIN": "ADMIN",
        /**
         * value: "SERVICE"
         * @const
         */
        "SERVICE": "SERVICE"    };

}
