/**
 * Sparkyservice API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AuthenticationInfoDto from './model/AuthenticationInfoDto';
import ChangePasswordDto from './model/ChangePasswordDto';
import CredentialsDto from './model/CredentialsDto';
import ErrorDto from './model/ErrorDto';
import SettingsDto from './model/SettingsDto';
import TokenDto from './model/TokenDto';
import UserDto from './model/UserDto';
import UsernameDto from './model/UsernameDto';
import AuthControllerApi from './api/AuthControllerApi';
import RoutingControllerApi from './api/RoutingControllerApi';
import UserControllerApi from './api/UserControllerApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SparkyserviceApi = require('index'); // See note below*.
* var xxxSvc = new SparkyserviceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SparkyserviceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SparkyserviceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SparkyserviceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1-SNAPSHOT
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticationInfoDto model constructor.
     * @property {module:model/AuthenticationInfoDto}
     */
    AuthenticationInfoDto,

    /**
     * The ChangePasswordDto model constructor.
     * @property {module:model/ChangePasswordDto}
     */
    ChangePasswordDto,

    /**
     * The CredentialsDto model constructor.
     * @property {module:model/CredentialsDto}
     */
    CredentialsDto,

    /**
     * The ErrorDto model constructor.
     * @property {module:model/ErrorDto}
     */
    ErrorDto,

    /**
     * The SettingsDto model constructor.
     * @property {module:model/SettingsDto}
     */
    SettingsDto,

    /**
     * The TokenDto model constructor.
     * @property {module:model/TokenDto}
     */
    TokenDto,

    /**
     * The UserDto model constructor.
     * @property {module:model/UserDto}
     */
    UserDto,

    /**
     * The UsernameDto model constructor.
     * @property {module:model/UsernameDto}
     */
    UsernameDto,

    /**
    * The AuthControllerApi service constructor.
    * @property {module:api/AuthControllerApi}
    */
    AuthControllerApi,

    /**
    * The RoutingControllerApi service constructor.
    * @property {module:api/RoutingControllerApi}
    */
    RoutingControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
